In [1]:
# Q1. Pandas version
import pandas as pd
print(pd.__version__)

3.0.3

In [2]:
# Read dataset
car_fuel_eff_df = pd.read_csv('datasets/car_fuel_efficiency_2026.csv')
car_fuel_eff_df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [3]:
# Q2. Record count
car_fuel_eff_df.shape

(10000, 11)

In [4]:
# Q3. Fuel types
car_fuel_eff_df["fuel_type"].nunique()

3

In [5]:
# Q4. Missing values
car_fuel_eff_df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [6]:
# Q5. Max fuel efficiency - Asia
car_fuel_eff_df_asia = car_fuel_eff_df[car_fuel_eff_df["origin"] == "Asia"]
car_fuel_eff_df_asia["fuel_efficiency_mpg"].max()

np.float64(41.2)

In [7]:
car_fuel_eff_df.columns

Index(['model_year', 'origin', 'fuel_type', 'drivetrain', 'num_doors',
       'engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'fuel_efficiency_mpg'],
      dtype='str')

In [8]:
# Q6. Median value of horsepower
# 1. Median
car_fuel_eff_df["horsepower"].median()

np.float64(254.0)

In [9]:
# 2. Frequent value
car_fuel_eff_df["horsepower"].mode()

0    252.0
Name: horsepower, dtype: float64

In [10]:
car_fuel_eff_df["horsepower"].isnull().sum()

np.int64(877)

In [11]:
# 3. Fill na with frequent value
car_fuel_eff_df["horsepower"] = car_fuel_eff_df["horsepower"].fillna(252)
car_fuel_eff_df

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0
...,...,...,...,...,...,...,...,...,...,...,...
9995,2005,USA,Gasoline,All-wheel drive,4,2470,6,271.0,4690,18.9,27.4
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0
9997,2014,USA,Gasoline,All-wheel drive,3,2480,6,267.0,4590,18.4,28.1
9998,2004,USA,Hybrid,Rear-wheel drive,5,2180,6,270.0,4450,20.9,32.2
9999,2011,USA,Diesel,Front-wheel drive,4,2380,6,295.0,4370,17.6,30.2

In [12]:
# 4. Median after fillna
car_fuel_eff_df["horsepower"].median()

np.float64(252.0)

In [13]:
# Q7. Sum of weights
# 1. Asia
car_fuel_eff_df_asia = car_fuel_eff_df[car_fuel_eff_df["origin"] == "Asia"]
# 2. Columns
car_fuel_eff_df_asia = car_fuel_eff_df_asia[["vehicle_weight","model_year"]]
# 3. Read 7 rows
car_fuel_eff_df_asia.head(7)

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [14]:
# 4. Numpy array
import numpy as np
X = np.array(car_fuel_eff_df_asia.head(7))
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [15]:
# 5. Matrix-Matrix multiplication
XTX = X.T.dot(X)
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [16]:
# 6. Inverse
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [17]:
# 7. Array y
y = [1100, 1300, 800, 900, 1000, 1100, 1200]

In [18]:
# 8. Result w
w = XTX_inv.dot(X.T).dot(y)
w

array([0.13644777, 0.2327492 ])

In [19]:
# 9. Sum of result elements
sum(w)

np.float64(0.36919696904925486)